name:                mcp
version:             0.1.0.0
github:              "mlang/mcp"
license:             BSD3
author:              "Mario Lang"
maintainer:          "mlang@blind.guru"
copyright:           "2019 Mario Lang"

description:         Marios Control Program

dependencies:
- aeson
- ansi-terminal
- base >= 4.9 && < 5
- bytestring
- diagrams-braille
- diagrams-core
- diagrams-lib
- directory
- exceptions
- ghc
- gi-glib
- gi-gst
- Glob
- gps
- haskeline >= 0.8.0.0
- haskell-gi-base
- hint
- http-client
- http-client-tls
- lens
- mtl
- parsers
- shh
- stm
- text
- transformers
- trifecta
- unix
- uri-encode
- wreq

library:
  source-dirs: lib

executables:
  mcp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mcp
